# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b37895d977ad50f064a0e662424baedac172abdab0cd13d0590cd6ae51a286a4a541b7700121ef2c24666d443817aa139dacb0c25e646f3720202ae2c8be0bd5

test:
  secret_key_base: 8a3943fb04a8ba02a7deee236f73dfd34cd270c8ae314677310f20348e9bfc417dd044ceb7b33b4ceb52c6d1e3a614d051e29ab94e2f6917e10d40003bc3b27f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
